export const variants = (mouseXPosition: number, mouseYPosition: number) => ({
  default: {
    opacity: mouseXPosition && mouseYPosition === 0 ? 0 : 1,
    height: 20,
    width: 20,
    fontSize: "16px",
    backgroundColor: "rgb(125, 91, 182)",
    x: mouseXPosition - 10,
    y: mouseYPosition - 10,
  },
  title: {
    opacity: 1,
    backgroundColor: "rgba(255, 255, 255, 1)",
    color: "rgba(255, 255, 255, 1)",
    height: 120,
    width: 120,
    fontSize: "18px",
    x: mouseXPosition - 60,
    y: mouseYPosition - 60,
    transition: {
      type: "spring",
    },
  },
  mainTitle: {
    opacity: 1,
    backgroundColor: "rgba(255, 255, 255, 1)",
    color: "rgba(255, 255, 255, 1)",
    height: 160,
    width: 160,
    fontSize: "18px",
    x: mouseXPosition - 80,
    y: mouseYPosition - 80,
    transition: {
      type: "spring",
    },
  },
  emoji: {
    opacity: 1,
    backgroundColor: "rgba(255, 255, 255, 1)",
    color: "rgba(255, 255, 255, 1)",
    height: 120,
    width: 120,
    fontSize: "18px",
    x: mouseXPosition - 60,
    y: mouseYPosition - 60,
    transition: {
      type: "spring",
    },
  },
  text: {
    opacity: 1,
    backgroundColor: "hsl(49, 91%, 52%)",
    color: "rgba(255, 255, 255, 1)",
    height: 40,
    width: 4,
    fontSize: "18px",
    x: mouseXPosition - 2,
    y: mouseYPosition - 20,
  },
  textImportant: {
    opacity: 1,
    backgroundColor: "rgba(255, 255, 255, 1)",
    color: "rgba(255, 255, 255, 1)",
    height: 60,
    width: 60,
    fontSize: "18px",
    x: mouseXPosition - 30,
    y: mouseYPosition - 30,
  },
  navLinks: {
    opacity: 0,
    height: 0,
    width: 0,
    x: mouseXPosition - 0,
    y: mouseYPosition - 0,
    transition: {
      type: "spring",
    },
  },
  popUpLinks: {
    opacity: 0,
    height: 0,
    width: 0,
    x: mouseXPosition - 0,
    y: mouseYPosition - 0,
    transition: {
      type: "spring",
    },
  },
  cursorButton: {
    opacity: 0,
    height: 0,
    width: 0,
    x: mouseXPosition - 0,
    y: mouseYPosition - 0,
    transition: {
      type: "spring",
    },
  },
  projectLink: {
    opacity: 1,
    backgroundColor: "rgb(125, 91, 182)",
    color: "rgba(255, 255, 255, 1)",
    height: 60,
    width: 60,
    fontSize: "18px",
    x: mouseXPosition - 50,
    y: mouseYPosition - 70,
    transition: {
      type: "spring",
    },
  },
  performance: {
    opacity: 1,
    backgroundColor: "hsl(265, 34%, 23%)",
    color: "rgba(255, 255, 255, 1)",
    height: 80,
    width: 80,
    fontSize: "18px",
    x: mouseXPosition - 130,
    y: mouseYPosition - 80,
    transition: {
      type: "spring",
    },
  },
  contact: {
    opacity: 1,
    backgroundColor: "rgba(255, 255, 255, 1)",
    color: "rgba(255, 255, 255, 1)",
    height: 80,
    width: 80,
    fontSize: "18px",
    x: mouseXPosition - 40,
    y: mouseYPosition - 40,
    transition: {
      type: "spring",
    },
  },
  sliderLeft: {
    opacity: 1,
    backgroundColor: "rgb(125, 91, 182)",
    color: "rgba(255, 255, 255, 1)",
    height: 60,
    width: 60,
    fontSize: "18px",
    x: mouseXPosition - 30,
    y: mouseYPosition - 30,
    transition: {
      type: "spring",
    },
  },
  sliderRight: {
    opacity: 1,
    backgroundColor: "rgb(125, 91, 182)",
    color: "rgba(255, 255, 255, 1)",
    height: 60,
    width: 60,
    fontSize: "18px",
    x: mouseXPosition - 30,
    y: mouseYPosition - 30,
    transition: {
      type: "spring",
    },
  },
});
